/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteRouteImport } from './routes/agent/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminPoliciesRouteImport } from './routes/admin/policies'
import { Route as AdminReceiptsRouteImport } from './routes/admin/receipts'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSoldPoliciesRouteImport } from './routes/admin/sold-policies'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AgentChangePasswordRouteImport } from './routes/agent/change-password'
import { Route as AgentCustomersRouteImport } from './routes/agent/customers'
import { Route as AgentDashboardRouteImport } from './routes/agent/dashboard'
import { Route as AgentGoalsRouteImport } from './routes/agent/goals'
import { Route as AgentNotesRouteImport } from './routes/agent/notes'
import { Route as AgentPoliciesRouteImport } from './routes/agent/policies'
import { Route as AgentProfileRouteImport } from './routes/agent/profile'
import { Route as AgentSellPolicyRouteImport } from './routes/agent/sell-policy'
import { Route as AgentSoldPoliciesRouteImport } from './routes/agent/sold-policies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRouteRoute = AgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReceiptsRoute = AdminReceiptsRouteImport.update({
  id: '/admin/receipts',
  path: '/admin/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSoldPoliciesRoute = AdminSoldPoliciesRouteImport.update({
  id: '/admin/sold-policies',
  path: '/admin/sold-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentChangePasswordRoute = AgentChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentCustomersRoute = AgentCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentGoalsRoute = AgentGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentNotesRoute = AgentNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentPoliciesRoute = AgentPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentProfileRoute = AgentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentSellPolicyRoute = AgentSellPolicyRouteImport.update({
  id: '/sell-policy',
  path: '/sell-policy',
  getParentRoute: () => AgentRouteRoute,
} as any)
const AgentSoldPoliciesRoute = AgentSoldPoliciesRouteImport.update({
  id: '/sold-policies',
  path: '/sold-policies',
  getParentRoute: () => AgentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sold-policies': typeof AdminSoldPoliciesRoute
  '/agent/change-password': typeof AgentChangePasswordRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/goals': typeof AgentGoalsRoute
  '/agent/notes': typeof AgentNotesRoute
  '/agent/policies': typeof AgentPoliciesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/sell-policy': typeof AgentSellPolicyRoute
  '/agent/sold-policies': typeof AgentSoldPoliciesRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sold-policies': typeof AdminSoldPoliciesRoute
  '/agent/change-password': typeof AgentChangePasswordRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/goals': typeof AgentGoalsRoute
  '/agent/notes': typeof AgentNotesRoute
  '/agent/policies': typeof AgentPoliciesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/sell-policy': typeof AgentSellPolicyRoute
  '/agent/sold-policies': typeof AgentSoldPoliciesRoute
  '/agent': typeof AgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/receipts': typeof AdminReceiptsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sold-policies': typeof AdminSoldPoliciesRoute
  '/agent/change-password': typeof AgentChangePasswordRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/goals': typeof AgentGoalsRoute
  '/agent/notes': typeof AgentNotesRoute
  '/agent/policies': typeof AgentPoliciesRoute
  '/agent/profile': typeof AgentProfileRoute
  '/agent/sell-policy': typeof AgentSellPolicyRoute
  '/agent/sold-policies': typeof AgentSoldPoliciesRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/login'
    | '/admin/agents'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/policies'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sold-policies'
    | '/agent/change-password'
    | '/agent/customers'
    | '/agent/dashboard'
    | '/agent/goals'
    | '/agent/notes'
    | '/agent/policies'
    | '/agent/profile'
    | '/agent/sell-policy'
    | '/agent/sold-policies'
    | '/agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/agents'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/policies'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sold-policies'
    | '/agent/change-password'
    | '/agent/customers'
    | '/agent/dashboard'
    | '/agent/goals'
    | '/agent/notes'
    | '/agent/policies'
    | '/agent/profile'
    | '/agent/sell-policy'
    | '/agent/sold-policies'
    | '/agent'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/login'
    | '/admin/agents'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/policies'
    | '/admin/receipts'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/sold-policies'
    | '/agent/change-password'
    | '/agent/customers'
    | '/agent/dashboard'
    | '/agent/goals'
    | '/agent/notes'
    | '/agent/policies'
    | '/agent/profile'
    | '/agent/sell-policy'
    | '/agent/sold-policies'
    | '/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRouteRoute: typeof AgentRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminReceiptsRoute: typeof AdminReceiptsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSoldPoliciesRoute: typeof AdminSoldPoliciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/receipts': {
      id: '/admin/receipts'
      path: '/admin/receipts'
      fullPath: '/admin/receipts'
      preLoaderRoute: typeof AdminReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sold-policies': {
      id: '/admin/sold-policies'
      path: '/admin/sold-policies'
      fullPath: '/admin/sold-policies'
      preLoaderRoute: typeof AdminSoldPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/change-password': {
      id: '/agent/change-password'
      path: '/change-password'
      fullPath: '/agent/change-password'
      preLoaderRoute: typeof AgentChangePasswordRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/customers': {
      id: '/agent/customers'
      path: '/customers'
      fullPath: '/agent/customers'
      preLoaderRoute: typeof AgentCustomersRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/goals': {
      id: '/agent/goals'
      path: '/goals'
      fullPath: '/agent/goals'
      preLoaderRoute: typeof AgentGoalsRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/notes': {
      id: '/agent/notes'
      path: '/notes'
      fullPath: '/agent/notes'
      preLoaderRoute: typeof AgentNotesRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/policies': {
      id: '/agent/policies'
      path: '/policies'
      fullPath: '/agent/policies'
      preLoaderRoute: typeof AgentPoliciesRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/profile': {
      id: '/agent/profile'
      path: '/profile'
      fullPath: '/agent/profile'
      preLoaderRoute: typeof AgentProfileRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/sell-policy': {
      id: '/agent/sell-policy'
      path: '/sell-policy'
      fullPath: '/agent/sell-policy'
      preLoaderRoute: typeof AgentSellPolicyRouteImport
      parentRoute: typeof AgentRouteRoute
    }
    '/agent/sold-policies': {
      id: '/agent/sold-policies'
      path: '/sold-policies'
      fullPath: '/agent/sold-policies'
      preLoaderRoute: typeof AgentSoldPoliciesRouteImport
      parentRoute: typeof AgentRouteRoute
    }
  }
}

interface AgentRouteRouteChildren {
  AgentChangePasswordRoute: typeof AgentChangePasswordRoute
  AgentCustomersRoute: typeof AgentCustomersRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentGoalsRoute: typeof AgentGoalsRoute
  AgentNotesRoute: typeof AgentNotesRoute
  AgentPoliciesRoute: typeof AgentPoliciesRoute
  AgentProfileRoute: typeof AgentProfileRoute
  AgentSellPolicyRoute: typeof AgentSellPolicyRoute
  AgentSoldPoliciesRoute: typeof AgentSoldPoliciesRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteRouteChildren: AgentRouteRouteChildren = {
  AgentChangePasswordRoute: AgentChangePasswordRoute,
  AgentCustomersRoute: AgentCustomersRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentGoalsRoute: AgentGoalsRoute,
  AgentNotesRoute: AgentNotesRoute,
  AgentPoliciesRoute: AgentPoliciesRoute,
  AgentProfileRoute: AgentProfileRoute,
  AgentSellPolicyRoute: AgentSellPolicyRoute,
  AgentSoldPoliciesRoute: AgentSoldPoliciesRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteRouteWithChildren = AgentRouteRoute._addFileChildren(
  AgentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRouteRoute: AgentRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminReceiptsRoute: AdminReceiptsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSoldPoliciesRoute: AdminSoldPoliciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
